import Head from 'next/head';
import styles from '../styles/Home.module.css';
import sitePermissionsJson from '../mocks/sitePermissions.json';
import belgo from '../mocks/belgo.json'
import ReportTable from '../src/components/ReportTable';

export default function Home() {

  // const sitePermFinal = checkSitePerm(sitePermissions as ISitePermission[]);
  const sitePermissions = sitePermissionsJson as ISitePermission[];

  const relatorio = gerarRelatorio(sitePermissions);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <pre className={styles.code}>
          {JSON.stringify(relatorio, null, 4)}
          <ReportTable relatorio={relatorio} />
        </pre>
      </main>
    </>
  )
}

const itemReport: IItemReport = {
  IdDefinicao: null,
  Site: null,
  Entidade: null,
  HerdaPermissao: null,
  DeveriaHerdarPermissao: null,
  Lista: null,
  IdItem: null,
  TemPermissao: null,
  DeveriaTerPermissao: null,
  Erro: false,
  Mensagem: ''
}

function gerarRelatorio(itens: ISitePermission[]) {

  let final: IItemReport[] = [];

  itens.forEach(item => {

    final.push({
      IdDefinicao: item.Id,
      Site: null,
      Entidade: null,
      HerdaPermissao: null,
      DeveriaHerdarPermissao: null,
      Lista: null,
      IdItem: null,
      TemPermissao: null,
      DeveriaTerPermissao: null,
      Erro: false,
      Mensagem: ''
    })
  })

  return final;
}



function checkSitePerm(perm: ISitePermission) {

  let finalReport = itemReport;
  finalReport.IdDefinicao = perm.Id;
  finalReport.Site = perm.URLSite.Title;
  finalReport.Entidade = perm.TipoEntidade;

  return finalReport
}